apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
  - name: website-content
    persistentVolumeClaim:
      claimName: ubuntu-pvc
  containers:
  - name: nginx
    image: nginx:1.21.6-alpine
    ports:
    - containerPort: 80
      name: http
      protocol: TCP   
    volumeMounts:
    - name: website-content
      mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: website-build-script
data:
  build-script.sh: |
    #!/bin/bash
    apt-get update && apt-get install -y git wget tar
    wget -qO- https://github.com/gohugoio/hugo/releases/download/v0.94.0/hugo_extended_0.94.0_Linux-64bit.tar.gz | tar xvz
    mv hugo /usr/local/bin/
    git clone --recursive https://github.com/chazapis/hy548.git
    cd ./hy548
    git submodule update --init --recursive
    cd ./html
    hugo -D
    cp -r ./public/* /website
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ubuntu
spec:
  template:
    spec:
      volumes:
      - name: script-volume
        configMap:
          name: website-build-script
      - name: website-content
        persistentVolumeClaim:
          claimName: ubuntu-pvc
      restartPolicy: OnFailure
      containers:
      - name: website-builder
        image: ubuntu:20.04
        command: ["/bin/bash", "/scripts/build-script.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        - name: website-content
          mountPath: /website
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ubuntu
spec:
  schedule: "15 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: script-volume
            configMap:
              name: website-build-script
          - name: website-content
            persistentVolumeClaim:
              claimName: ubuntu-pvc
          restartPolicy: OnFailure
          containers:
          - name: website-builder
            image: ubuntu:20.04
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
            - name: website-content
              mountPath: /website
            command: ["/bin/bash", "/scripts/build-script.sh"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pvc
spec:
  storageClassName: ""
  volumeName: ubuntu-pv
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubuntu-pv
spec:
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 1Gi
  hostPath:
    path: /website
